# Neural network from scratch

### Packages

In [2]:
import numpy as np
import pandas as pd

### Data

In [3]:
df = pd.read_csv("SNADs.csv")
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [4]:
x_features = ["Age","EstimatedSalary"]
x_train = df[x_features].values

y_train = df["Purchased"].values

### Sigmoid Function

In [5]:
def g(z):
    return 1/(1+np.exp(-z))

### Neural Network without vectorization

activation sigmoid function

In [6]:
def dense_wv(a_in,W,b):
    
    units = W.shape[1]
    
    a_out = np.zeros(units)
    
    for i in range(units):
        
        a_out[i] = g(np.dot(W[:,i],a_in)+b[i])
        
    return a_out

### Neural Network with vectorization

activation sigmoid function

In [7]:
def dense(a_in,W,b):
    
    a_out = g(np.matmul(a_in,W)+b)
    
    return a_out

In [8]:
W1 = np.array([[1,2,3],
             [2,3,4]])
b1 = np.array([1,2,3])

W2 = np.array([[1],[2],[3]])
b2 = np.array([1])

### without vectorization

In [9]:
a_1 = dense_wv(x_train[0],W1,b1)
a_1

array([1., 1., 1.])

In [10]:
a_2 = dense_wv(a_1,W2,b2)
a_2

array([0.99908895])

### with vectorization

In [11]:
a_1 = dense_wv(x_train[0],W1,b1)
a_1

array([1., 1., 1.])

In [12]:
a_2 = dense_wv(a_1,W2,b2)
a_2

array([0.99908895])